<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bsv</string>
	</array>
	<key>name</key>
	<string>Bluespec</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(#|@)</string>
			<key>name</key>
			<string>keyword.other.bluespec</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.bluespec</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.import.bluespec</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(import)\s+(.*)$</string>
			<key>name</key>
			<string>meta.import.bluespec</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#all-types</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Action|ActionValue|BVI|C|CF|E|SB|SBR|action|endaction|actionvalue|endactionvalue|ancestor|begin|bit|case|endcase|clocked_by|default|default_clock|default_reset|dependencies|deriving|determines|e|else|enable|end|enum|export|for|function|endfunction|if|ifc_inout|inout|input_clock|input_reset|instance|endinstance|interface|endinterface|let|match|matches|method|endmethod|module|endmodule|numeric|output_clock|output_reset|package|endpackage|parameter|path|port|provisos|reset_by|return|rule|endrule|rules|endrules|same_family|schedule|struct|tagged|type|typeclass|endtypeclass|typedef|union|valueOf|valueof|void|while)\b</string>
			<key>name</key>
			<string>keyword.other.bluespec</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|begin|end|function|endfunction|endmodule)\b</string>
			<key>name</key>
			<string>keyword.control.bluespec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.bluespec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|\/|%|=)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.bluespec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|&amp;&amp;|\|\|)</string>
			<key>name</key>
			<string>keyword.operator.logical.bluespec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&amp;|\||\^|~\^|\^~|~|&lt;&lt;|&gt;&gt;|\?|:|~&amp;|~\|)</string>
			<key>name</key>
			<string>keyword.operator.bitwise.bluespec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(pack|unpack)\b</string>
			<key>name</key>
			<string>keyword.operator.other.bluespec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b\d+)?'([bB]\s*[0-1_xXzZ?]+|[oO]\s*[0-7_xXzZ?]+|[dD]\s*[0-9_xXzZ?]+|[hH]\s*[0-9a-fA-F_xXzZ?]+)((e|E)(\+|-)?[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.bluespec</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#illegal-verilog</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>all-types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#storage-datatype-bluespec</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storage-typeclass-bluespec</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.bluespec</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.bluespec</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.bluespec</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.bluespec</string>
				</dict>
			</array>
		</dict>
		<key>illegal-verilog</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(alias|always|always_comb|always_ff|always_latch|and|assert|assert_strobe|assign|assume|automatic)\b</string>
					<key>name</key>
					<string>invalid.illegal.verilog-keywords.bluespec</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bind|bins|binsof|break|buf|bufif0|bufif1|byte|casex|casez|cell|chandle|class|endclass|clocking|endclocking|cmos|config|endconfig|const|constraint|context|continue|cover|covergroup|endgroup|coverpoint|cross)\b</string>
					<key>name</key>
					<string>invalid.illegal.verilog-keywords.bluespec</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(deassign|defparam|design|disable|dist|do|edge|event|expect|extends|extern|final|first_match|force|foreach|forever|fork|forkjoin|generate|endgenerate|genvar|highz0|highz1|iff|ifnone|ignore_bins|illegal_bins|incdir|include|initial|input|inside|int|integer|intersect)\b</string>
					<key>name</key>
					<string>invalid.illegal.verilog-keywords.bluespec</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(join|join_any|join_none|large|liblist|library|local|localparam|logic|longint|macromodule|medium|medium|modport|nand|negedge|new|nmos|nor|noshowcancelled|not|notif0|notif1|null|or|output|packed|pmos|posedge|primitive|endprimitive|priority|program|endprogram|property|endproperty|protected|pull0|pull1|pulldown|pullup|pulsestyle_onevent|pulsestyle_ondetect|pure)\b</string>
					<key>name</key>
					<string>invalid.illegal.verilog-keywords.bluespec</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(rand|randc|randcase|randsequence|rcmos|real|realtime|ref|reg|release|repeat|rnmos|rpmos|rtran|rtranif0|rtranif1|scalared|sequence|endsequence|shortint|shortreal|showcancelled|signed|small|solve|specify|endspecify|specparam|static|string|strong0|strong1|super|supply0|supply1)\b</string>
					<key>name</key>
					<string>invalid.illegal.verilog-keywords.bluespec</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(table|endtable|task|endtask|this|throughout|time|timeprecision|timeunit|tran|tranif0|tranif1|tri|tri0|tri1|triand|trior|trireg|unique|unsigned|use|var|vectored|virtual|wait|wait_order|wand|weak0|weak1|wildcard|wire|with|within|wor|xnor|xor)\b</string>
					<key>name</key>
					<string>invalid.illegal.verilog-keywords.bluespec</string>
				</dict>
			</array>
		</dict>
		<key>storage-datatype-bluespec</key>
		<dict>
			<key>match</key>
			<string>\b(Bit|bit|UInt|Int|int|Integer|Bool|Real|real|String|FIFO|FIFOF|Fmt|Void|void|Maybe|Ordering|Tuple[2345678]|Clock|Reset|Inout|Action|ActionValue|Rules|Reg|Wire|RWire|BypassWire|DWire|PulseWire|ReadOnly|WriteOnly)\b</string>
			<key>name</key>
			<string>storage.type.bluespec</string>
		</dict>
		<key>storage-typeclass-bluespec</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(Bits|Eq|Literal|RealLiteral|SizedLiteral|Arith|Ord|Bounded|Bitwise|BitReduction|BitExtend|SaturatingArith|Alias|NumAlias)\b</string>
					<key>name</key>
					<string>storage.type.bluespec</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Add|Mul|Div|Max|Min|Log|TAdd|TSub|TMul|TDiv|TLog|TExp|TMax|TMin)\b</string>
					<key>name</key>
					<string>storage.type.bluespec</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.verilog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.verilog</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.verilog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.verilog</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bluespec</string>
	<key>uuid</key>
	<string>15b0b35d-eaef-423b-b588-07b2d5976324</string>
</dict>
</plist>
